server:
  port: 8080
spring:
  application:
    name: "cleanArchitecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://davidjulm_db_user:I8clnVQsaJjl4eZo@ciudadela-futuro.pv5mcln.mongodb.net/?retryWrites=true&w=majority&appName=ciudadela-futuro"
      database: "ciudadela_futuro_db"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
